#!/bin/sh
# Generates the `postgram_mcp` upstream that ui/nginx.conf proxies to.
#
# Per-request (periodic) re-resolution of mcp-server is only safe where the
# container's resolver answers for bare service names. That is guaranteed on
# Docker's embedded DNS (127.0.0.11, user-defined networks), which is also
# where recreating mcp-server hands it a new IP. Elsewhere (Kubernetes,
# Podman, network_mode: host, --add-host) nginx's own resolver would bypass
# /etc/hosts and resolv.conf search domains and every API call would 502, so
# the upstream is resolved once at startup by the system resolver, as a
# literal proxy_pass always was.
#
# NGINX_RESOLVER overrides the detection:
#   unset/empty  auto-detect as above
#   off          always resolve once at startup
#   <address>    re-resolve through this DNS server (e.g. 10.89.0.1 for
#                Podman's aardvark-dns); the name must resolve there as-is
set -eu

out=/etc/nginx/conf.d/00-postgram-mcp-upstream.conf
upstream_server=mcp-server:3100
resolver="${NGINX_RESOLVER:-}"

if [ -z "$resolver" ]; then
  first_ns=$(awk '$1 == "nameserver" { print $2; exit }' /etc/resolv.conf 2>/dev/null || true)
  if [ "$first_ns" = "127.0.0.11" ]; then
    resolver=127.0.0.11
  else
    resolver=off
  fi
fi

if [ "$resolver" = "off" ]; then
  cat > "$out" <<CONF
# Generated by 40-postgram-mcp-upstream.sh: resolved once at startup.
upstream postgram_mcp {
  server $upstream_server;
}
CONF
  echo "$0: info: mcp-server resolved once at startup (NGINX_RESOLVER=off or no Docker embedded DNS)"
  exit 0
fi

case "$resolver" in
  *:*) case "$resolver" in \[*) ;; *) resolver="[$resolver]" ;; esac ;;
esac

cat > "$out" <<CONF
# Generated by 40-postgram-mcp-upstream.sh: re-resolved every 10s.
resolver $resolver valid=10s ipv6=off;
upstream postgram_mcp {
  zone postgram_mcp 64k;
  server $upstream_server resolve;
}
CONF
echo "$0: info: mcp-server re-resolved every 10s via $resolver"
